# Generated by Django 5.1.1 on 2024-10-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fokontanyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuable',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='contribuable',
            name='district',
        ),
        migrations.RemoveField(
            model_name='contribuable',
            name='region',
        ),
        migrations.AlterModelTable(
            name='fokontanyview',
            table='v_getfokontany',
        ),
    ]
