# Generated by Django 5.1.1 on 2024-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_contribuable_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='fokontany',
            field=models.IntegerField(),
        ),
    ]
