# Generated by Django 5.1.1 on 2024-10-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_centralrecette_prenif'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueRecouvrementsEtPaiementsParAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuable', models.IntegerField()),
                ('annee_recouvrement', models.IntegerField()),
                ('total_recouvrement_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paye_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vue_recouvrements_et_paiements_par_annee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueSommeParContribuableParAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuable', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('total_mnt_ver', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'vue_somme_par_contribuable_par_annee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VueTransactionsParQuitEtContribuable',
            fields=[
                ('contribuable', models.IntegerField()),
                ('n_quit', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mont_ap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_payee', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reste_ap', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'vue_transactions_par_quit_et_contribuable',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/faces/'),
        ),
    ]
