# Generated by Django 5.1.1 on 2024-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_vuerecouvrementsetpaiementsparannee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuable', models.IntegerField()),
                ('n_quit', models.CharField(max_length=50)),
                ('date_paiement', models.DateField()),
                ('annee_de_paiement', models.IntegerField()),
                ('annee_recouvrement', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mnt_ap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nimp', models.IntegerField()),
                ('imp_detail', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=50)),
                ('impot', models.CharField(max_length=50)),
                ('sens', models.CharField(max_length=50)),
                ('logiciel', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'Transaction Detail',
                'verbose_name_plural': 'Transaction Details',
                'db_table': 'vue_detail_transactions_par_quit_et_contribuable',
                'managed': False,
            },
        ),
    ]
