# Generated by Django 5.1.1 on 2024-11-11 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_transactiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, null=True)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='messages_fichiers/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('type_message', models.CharField(choices=[('contribuable', 'Contribuable'), ('operateur', 'Opérateur')], max_length=20)),
                ('id_contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contribuable')),
                ('id_operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.operateur')),
            ],
        ),
    ]
