# Generated by Django 5.1.1 on 2024-11-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_message_id_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notifié',
            field=models.BooleanField(default=False),
        ),
    ]
