# Generated by Django 5.1.1 on 2024-12-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_message_notifié'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='mot_de_passe',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
