# Generated by Django 5.1.4 on 2025-01-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_centralrecette_numrec_paiement_numrec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='myapp.contribuable')),
            ],
        ),
    ]
