# Generated by Django 5.1.4 on 2025-04-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux_droit_enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_droit', models.CharField(max_length=200)),
                ('taux', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_imposable', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mnt_ap', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('id_contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contribuable')),
                ('id_tde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.taux_droit_enregistrement')),
            ],
        ),
    ]
