# Generated by Django 5.1.1 on 2024-10-08 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sit_matrim_delete_user_alter_genre_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('lieu_delivrance', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('date_delivrance', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('fokontany', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.genre')),
                ('situation_matrimoniale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.sit_matrim')),
            ],
        ),
    ]
