# Generated by Django 5.1.1 on 2024-10-09 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contribuable'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
                ('city_name_f', models.CharField(blank=True, max_length=25, null=True)),
                ('city_name_s', models.CharField(blank=True, max_length=25, null=True)),
                ('city_code', models.CharField(max_length=5)),
                ('city_name_extra', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_name_f', models.CharField(blank=True, max_length=20, null=True)),
                ('country_name_s', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(max_length=4)),
                ('capital', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_desc', models.CharField(max_length=30)),
                ('locality_desc_f', models.CharField(blank=True, max_length=30, null=True)),
                ('locality_desc_s', models.CharField(blank=True, max_length=30, null=True)),
                ('locality_code', models.CharField(max_length=6)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parish_name', models.CharField(max_length=35)),
                ('parish_name_f', models.CharField(blank=True, max_length=35, null=True)),
                ('parish_name_s', models.CharField(blank=True, max_length=35, null=True)),
                ('parish_code', models.CharField(max_length=4)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parish'),
        ),
        migrations.CreateModel(
            name='Wereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wereda_desc', models.CharField(max_length=50)),
                ('wereda_code', models.IntegerField()),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.locality')),
            ],
        ),
        migrations.CreateModel(
            name='Fokontany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fkt_desc', models.CharField(max_length=500)),
                ('wereda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.wereda')),
            ],
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
