# Generated by Django 5.1.1 on 2024-10-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_operateur_alter_contribuable_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logiciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logiciel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NumImpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impot', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CentralRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_centre_recette', models.CharField(max_length=200)),
                ('regisseur', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ref_trans', models.CharField(blank=True, max_length=60, null=True)),
                ('ref_reglement', models.CharField(blank=True, max_length=60, null=True)),
                ('daty', models.DateField(blank=True, null=True)),
                ('mouvement', models.CharField(default='0', max_length=1)),
                ('moyen_paiement', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('rib', models.CharField(blank=True, max_length=30, null=True)),
                ('prenif', models.CharField(blank=True, max_length=20, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=250, null=True)),
                ('numrec', models.IntegerField(blank=True, null=True)),
                ('libelle', models.CharField(blank=True, max_length=20, null=True)),
                ('flag', models.CharField(default='N', max_length=1)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('periode', models.IntegerField(default=1)),
                ('periode2', models.CharField(blank=True, max_length=10, null=True)),
                ('mnt_ap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('base', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('imp_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('da', models.IntegerField(default=0)),
                ('banque', models.CharField(blank=True, max_length=75, null=True)),
                ('annee_recouvrement', models.IntegerField(blank=True, null=True)),
                ('code_bureau', models.CharField(blank=True, max_length=250, null=True)),
                ('libelle_bureau', models.CharField(blank=True, max_length=250, null=True)),
                ('id_contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contribuable')),
                ('logiciel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logiciel')),
                ('nimp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.numimpot')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_quit', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('central_recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.centralrecette')),
                ('id_contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contribuable')),
                ('mode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.modepaiement')),
            ],
        ),
    ]
