# Generated by Django 5.1.1 on 2024-12-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_contribuable_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPublicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la vidéo publicitaire', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description ou contenu de la vidéo')),
                ('video', models.FileField(blank=True, help_text='Fichier vidéo local', null=True, upload_to='videos/')),
                ('lien_video', models.URLField(blank=True, help_text='Lien externe pour la vidéo', null=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True, help_text='Date de publication')),
                ('duree', models.DurationField(blank=True, help_text='Durée de la vidéo (HH:MM:SS)', null=True)),
                ('categorie', models.CharField(blank=True, help_text='Catégorie de la publicité', max_length=100)),
                ('langue', models.CharField(blank=True, help_text='Langue principale de la vidéo', max_length=50)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', help_text='Statut de la vidéo', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Tags ou mots-clés pour la recherche', max_length=255)),
                ('nombre_vues', models.PositiveIntegerField(default=0, help_text='Nombre de vues de la vidéo')),
                ('auteur', models.CharField(blank=True, help_text='Auteur de la vidéo', max_length=255)),
                ('miniature', models.ImageField(blank=True, help_text='Miniature pour la vidéo', null=True, upload_to='thumbnails/')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Vidéo Publicitaire',
                'verbose_name_plural': 'Vidéos Publicitaires',
                'ordering': ['-date_publication'],
            },
        ),
    ]
