# Generated by Django 5.1.1 on 2024-12-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_videopublicite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fichier_pdf', models.FileField(upload_to='brochures_pdfs/')),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
