# Generated by Django 5.1.1 on 2024-12-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_brochure_fichier_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centralrecette',
            name='numrec',
        ),
        migrations.AddField(
            model_name='paiement',
            name='numrec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
